[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10.12"
discord-py = ">=2.5.2"
flask = ">=3.1.1"
python-dotenv = ">=1.1.1"
